### ISSUE TITLE
Replace Deployment dialog closes immediately after click in replace button

### ISSUE THREAD

**Issue by doleron** [hal/site#1]
Hi, first of all I apologize for open this issue in the _site_ project. I looked into the _console_ project but I couldn't find the _issues_ section there.
I'm moving from wildfly 10.X to 17.X. I realized that, in the _Replace_ operation under _Deployments_ area, the **_Replace Deployment_ dialog closes immediately after the click in the _Replace_ button**. I'm wondering if keeping the dialog opened with a status loop gif (like wildfly 10.x version does) may be worthy in order to provide an indication to the user about the upload/deployment in course. In current version (I'm using wildfly 17.0.1.Final) the only thing to do is to wait for the notification in the notification panel. In the absence of an indication, there is a risk to the user make a mistake inadvertently closing the browser or start another (or the same) deployment or so.

**Comment by hpehl** [comment]
Thanks for the suggestions. We use JIRA to track HAL issues: https://issues.jboss.org/projects/HAL/summary. Could you please file a feature request there? Thanks!

**Comment by doleron** [comment]
Hi Harald, I just created the jira's feature request: https://issues.jboss.org/browse/HAL-1629
